"""project resolutions and nullable project ids

Revision ID: 07c2a4dddca7
Revises: 0f622767793c
Create Date: 2026-06-13 20:50:15.430609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07c2a4dddca7'
down_revision: Union[str, Sequence[str], None] = '0f622767793c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_resolutions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('candidate_name', sa.String(), nullable=False),
    sa.Column('candidate_description', sa.Text(), nullable=True),
    sa.Column('candidate_project_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('resolved_project_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['resolved_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('people', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('teams', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('terms', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('terms', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('teams', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('people', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('project_resolutions')
    # ### end Alembic commands ###
