"""add facts table and make topic document_id nullable

Revision ID: 0c2e9967ae6c
Revises: 5f83175fddfc
Create Date: 2026-06-14 23:43:54.479304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2e9967ae6c'
down_revision: Union[str, Sequence[str], None] = '5f83175fddfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facts',
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('object_id', sa.UUID(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('topics', 'document_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topics', 'document_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('facts')
    # ### end Alembic commands ###
