"""add status to facts

Revision ID: 8705d5bd5e0e
Revises: 0c2e9967ae6c
Create Date: 2026-06-15 21:51:13.660482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8705d5bd5e0e'
down_revision: Union[str, Sequence[str], None] = '0c2e9967ae6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing facts were recorded under the old unconditional flow and were already
    # treated as live "Known facts"; default them to "confirmed" so behavior is
    # unchanged. New facts default to "pending" at the application level.
    op.add_column('facts', sa.Column('status', sa.String(), nullable=False, server_default='confirmed'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facts', 'status')
    # ### end Alembic commands ###
