"""add document origin and conversation attachments

Revision ID: 97e3959654de
Revises: 61d2f897e1d7
Create Date: 2026-07-08 23:31:54.669976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '97e3959654de'
down_revision: Union[str, Sequence[str], None] = '61d2f897e1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_attachments',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_attachments_conversation_id'), 'conversation_attachments', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_attachments_document_id'), 'conversation_attachments', ['document_id'], unique=False)
    op.add_column('documents', sa.Column('origin', sa.String(), server_default='ingested', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'origin')
    op.drop_index(op.f('ix_conversation_attachments_document_id'), table_name='conversation_attachments')
    op.drop_index(op.f('ix_conversation_attachments_conversation_id'), table_name='conversation_attachments')
    op.drop_table('conversation_attachments')
    # ### end Alembic commands ###
