"""add missing indexes and unique document path

Revision ID: f3da9f1b48fe
Revises: 8705d5bd5e0e
Create Date: 2026-06-18 18:56:24.513788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3da9f1b48fe'
down_revision: Union[str, Sequence[str], None] = '8705d5bd5e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_embedding_hnsw_cosine', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_documents_project_id'), 'documents', ['project_id'], unique=False)
    op.create_unique_constraint('uq_documents_path', 'documents', ['path'])
    op.create_index(op.f('ix_facts_object_id'), 'facts', ['object_id'], unique=False)
    op.create_index(op.f('ix_facts_subject_id'), 'facts', ['subject_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_people_document_id'), 'people', ['document_id'], unique=False)
    op.create_index(op.f('ix_people_project_id'), 'people', ['project_id'], unique=False)
    op.create_index(op.f('ix_people_team_id'), 'people', ['team_id'], unique=False)
    op.create_index(op.f('ix_project_resolutions_document_id'), 'project_resolutions', ['document_id'], unique=False)
    op.create_index(op.f('ix_project_resolutions_resolved_project_id'), 'project_resolutions', ['resolved_project_id'], unique=False)
    op.create_index(op.f('ix_relations_document_id'), 'relations', ['document_id'], unique=False)
    op.create_index(op.f('ix_relations_object_id'), 'relations', ['object_id'], unique=False)
    op.create_index(op.f('ix_relations_subject_id'), 'relations', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teams_document_id'), 'teams', ['document_id'], unique=False)
    op.create_index(op.f('ix_teams_project_id'), 'teams', ['project_id'], unique=False)
    op.create_index(op.f('ix_terms_document_id'), 'terms', ['document_id'], unique=False)
    op.create_index(op.f('ix_terms_project_id'), 'terms', ['project_id'], unique=False)
    op.create_index(op.f('ix_topics_document_id'), 'topics', ['document_id'], unique=False)
    op.create_index(op.f('ix_topics_project_id'), 'topics', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_project_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_document_id'), table_name='topics')
    op.drop_index(op.f('ix_terms_project_id'), table_name='terms')
    op.drop_index(op.f('ix_terms_document_id'), table_name='terms')
    op.drop_index(op.f('ix_teams_project_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_document_id'), table_name='teams')
    op.drop_index(op.f('ix_relations_subject_id'), table_name='relations')
    op.drop_index(op.f('ix_relations_object_id'), table_name='relations')
    op.drop_index(op.f('ix_relations_document_id'), table_name='relations')
    op.drop_index(op.f('ix_project_resolutions_resolved_project_id'), table_name='project_resolutions')
    op.drop_index(op.f('ix_project_resolutions_document_id'), table_name='project_resolutions')
    op.drop_index(op.f('ix_people_team_id'), table_name='people')
    op.drop_index(op.f('ix_people_project_id'), table_name='people')
    op.drop_index(op.f('ix_people_document_id'), table_name='people')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_facts_subject_id'), table_name='facts')
    op.drop_index(op.f('ix_facts_object_id'), table_name='facts')
    op.drop_constraint('uq_documents_path', 'documents', type_='unique')
    op.drop_index(op.f('ix_documents_project_id'), table_name='documents')
    op.drop_index('ix_chunks_embedding_hnsw_cosine', table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    # ### end Alembic commands ###
